export const contacts = [
  {
    firstName: "Devrim",
    lastName: "Abaci",
    cellPhone: "(678)231-4483",
    emailAddress: "devrimabaci2025@u.northwestern.edu",
  },
  {
    firstName: "Sheyla",
    lastName: "Adaya",
    cellPhone: "(224)334-4712",
    emailAddress: "sheylaadaya2024@u.northwestern.edu",
  },
  {
    firstName: "Lillian",
    lastName: "Ali",
    cellPhone: "(937)286-7767",
    emailAddress: "lillianali2026@u.northwestern.edu",
  },
  {
    firstName: "Mariama",
    lastName: "Bah",
    cellPhone: "(224)428-7873",
    emailAddress: "mariamabah2025@u.northwestern.edu",
  },
  {
    firstName: "Stewart",
    lastName: "Bridgeforth",
    cellPhone: "(703)470-5144",
    emailAddress: "stewartbridgeforth2024@u.northwestern.edu",
  },
  {
    firstName: "Kailyn",
    lastName: "Brown",
    cellPhone: "(470)385-7539",
    emailAddress: "kailynbrown2025@u.northwestern.edu",
  },
  {
    firstName: "Anna",
    lastName: "Castagnaro",
    cellPhone: "(321)317-1089",
    emailAddress: "annacastagnaro2024@u.northwestern.edu",
  },
  {
    firstName: "Jason",
    lastName: "Chen",
    cellPhone: "(781)952-9214",
    emailAddress: "jasonchen2026@u.northwestern.edu",
  },
  {
    firstName: "Yolanda",
    lastName: "Chen",
    cellPhone: "(626)362-0418",
    emailAddress: "yolandachen2024@u.northwestern.edu",
  },
  {
    firstName: "James",
    lastName: "Chou",
    cellPhone: "(929)316-4953",
    emailAddress: "yu-tienchou2024@u.northwestern.edu",
  },
  {
    firstName: "Chanelle",
    lastName: "Chu",
    cellPhone: "(669)208-8745",
    emailAddress: "chanellechu2026@u.northwestern.edu",
  },
  {
    firstName: "Filip",
    lastName: "Czarkowski",
    cellPhone: "(773)895-0714",
    emailAddress: "filipczarkowski2022@u.northwestern.edu",
  },
  {
    firstName: "Ellen",
    lastName: "Darmstadter",
    cellPhone: "(608)239-6227",
    emailAddress: "ellendarmstadter2026@u.northwestern.edu",
  },
  {
    firstName: "Sophie",
    lastName: "Denhard",
    cellPhone: "(206)450-8197",
    emailAddress: "sophiedenhard2024@u.northwestern.edu",
  },
  {
    firstName: "Ashwat",
    lastName: "Dhamotharan",
    cellPhone: "(248)775-9600",
    emailAddress: "ashwatdhamotharan2025@u.northwestern.edu",
  },
  {
    firstName: "Leilani",
    lastName: "Diaz",
    cellPhone: "(832)544-6509",
    emailAddress: "leilanidiaz2026@u.northwestern.edu",
  },
  {
    firstName: "Aldiery",
    lastName: "Gonzalez",
    cellPhone: "(407)867-1186",
    emailAddress: "aldierygonzalez2024@u.northwestern.edu",
  },
  {
    firstName: "Spencer",
    lastName: "Guy",
    cellPhone: "(615)686-9826",
    emailAddress: "spencerguy2025@u.northwestern.edu",
  },
  {
    firstName: "Lily",
    lastName: "Hoyt",
    cellPhone: "(978)808-3120",
    emailAddress: "lilyhoyt2025@u.northwestern.edu",
  },
  {
    firstName: "Scott",
    lastName: "Hwang",
    cellPhone: "(650)670-8220",
    emailAddress: "scotthwang2026@u.northwestern.edu",
  },
  {
    firstName: "Sophia",
    lastName: "Jedziniak",
    cellPhone: "(630)383-8599",
    emailAddress: "sophiajedziniak2026@u.northwestern.edu",
  },
  {
    firstName: "Ian",
    lastName: "Jeon",
    cellPhone: "(917)745-7871",
    emailAddress: "ianjeon2026@u.northwestern.edu",
  },
  {
    firstName: "Hyeyun",
    lastName: "Jeong",
    cellPhone: "(571)523-6575",
    emailAddress: "hyeyunjeong2025@u.northwestern.edu",
  },
  {
    firstName: "Nicholas",
    lastName: "Kapp",
    cellPhone: "(331)575-4944",
    emailAddress: "nicholaskapp2025@u.northwestern.edu",
  },
  {
    firstName: "Ethan",
    lastName: "Karas",
    cellPhone: "(914)323-8530",
    emailAddress: "ethankaras2019@u.northwestern.edu",
  },
  {
    firstName: "Daniel",
    lastName: "Kinney",
    cellPhone: "(585)200-6578",
    emailAddress: "danielkinney2026@u.northwestern.edu",
  },
  {
    firstName: "Soraya",
    lastName: "Koblence",
    cellPhone: "(917)209-9554",
    emailAddress: "sorayakoblence2024@u.northwestern.edu",
  },
  {
    firstName: "Oliver",
    lastName: "Koenig",
    cellPhone: "(646)599-0323",
    emailAddress: "oliverkoenig2026@u.northwestern.edu",
  },
  {
    firstName: "James",
    lastName: "La Fayette",
    cellPhone: "(813)347-1840",
    emailAddress: "Jameslafayette2026@u.northwestern.edu",
  },
  {
    firstName: "Alexander",
    lastName: "Lake",
    cellPhone: "(415)996-8554",
    emailAddress: "alexlake2025@u.northwestern.edu",
  },
  {
    firstName: "Jiho",
    lastName: "Lee",
    cellPhone: "(241)846-0420",
    emailAddress: "jiholee2026@u.northwestern.edu",
  },
  {
    firstName: "Brian",
    lastName: "Lin",
    cellPhone: "(909)996-8837",
    emailAddress: "brianlin2025@u.northwestern.edu",
  },
  {
    firstName: "Mercy",
    lastName: "Olayiwola",
    cellPhone: "(860)518-8053",
    emailAddress: "rjolayiwola2023@u.northwestern.edu",
  },
  {
    firstName: "Kevin",
    lastName: "Opeña",
    cellPhone: "(847)830-1839",
    emailAddress: "kevinopena2024@u.northwestern.edu",
  },
  {
    firstName: "Sebastian",
    lastName: "Ortiz",
    cellPhone: "(872)292-2693",
    emailAddress: "sebastianrrtiz2023@u.northwestern.edu",
  },
  {
    firstName: "Freya",
    lastName: "Ou",
    cellPhone: "(224)714-7942",
    emailAddress: "freyaou2024@u.northwestern.edu",
  },
  {
    firstName: "Ryan",
    lastName: "Payne",
    cellPhone: "(571)320-7536",
    emailAddress: "ryanpayne2026@u.northwestern.edu",
  },
  {
    firstName: "Eliza",
    lastName: "Reimold",
    cellPhone: "(978)237-2669",
    emailAddress: "elizareimold2025@u.northwestern.edu",
  },
  {
    firstName: "Jeffrey",
    lastName: "Ryan",
    cellPhone: "(615)569-8723",
    emailAddress: "jeffreyryan2025@u.northwestern.edu",
  },
  {
    firstName: "Angel",
    lastName: "Salinas",
    cellPhone: "(346)932-9392",
    emailAddress: "angelsalinas2025@u.northwestern.edu",
  },
  {
    firstName: "Pablo",
    lastName: "Schnelle",
    cellPhone: "(832)540-5021",
    emailAddress: "pabloschnelle2024@u.northwestern.edu",
  },
  {
    firstName: "Claire",
    lastName: "Shen",
    cellPhone: "(614)356-0536",
    emailAddress: "claireshen2026@u.northwestern.edu",
  },
  {
    firstName: "Chele",
    lastName: "Shuart",
    cellPhone: "(989)254-3451",
    emailAddress: "chelewynneshuart2023@u.northwestern.edu",
  },
  {
    firstName: "Ann",
    lastName: "Slivken",
    cellPhone: "(847)736-3447",
    emailAddress: "annslivken2026@u.northwestern.edu",
  },
  {
    firstName: "Jackson",
    lastName: "Spellman",
    cellPhone: "(561)603-3834",
    emailAddress: "jacksonspellman2025@u.northwestern.edu",
  },
  {
    firstName: "Lauren",
    lastName: "Tan",
    cellPhone: "(301)648-4167",
    emailAddress: "laurentan2026@u.northwestern.edu",
  },
  {
    firstName: "Emma",
    lastName: "Truong",
    cellPhone: "(773)754-9361",
    emailAddress: "emmatruong2024@u.northwestern.edu",
  },
  {
    firstName: "Julianna",
    lastName: "Wang",
    cellPhone: "(980)259-8081",
    emailAddress: "juliannawang2025@u.northwestern.edu",
  },
  {
    firstName: "Serge",
    lastName: "Wen",
    cellPhone: "(773)681-6185",
    emailAddress: "sergewen2025@u.northwestern.edu",
  },
  {
    firstName: "Haylie",
    lastName: "Wu",
    cellPhone: "(669)264-8245",
    emailAddress: "hayliewu2024@u.northwestern.edu",
  },
  {
    firstName: "Elliott",
    lastName: "Yoon",
    cellPhone: "(440)840-8549",
    emailAddress: "elliottyoon2025@u.northwestern.edu",
  },
  {
    firstName: "Kyle",
    lastName: "Yuen",
    cellPhone: "(510)683-1967",
    emailAddress: "kyleyuen2026@u.northwestern.edu",
  },
  {
    firstName: "Alina",
    lastName: "Zhang",
    cellPhone: "(773)290-4697",
    emailAddress: "alinazhang2024@u.northwestern.edu",
  },
  {
    firstName: "Joshua",
    lastName: "Zhuang",
    cellPhone: "(561)631-7583",
    emailAddress: "joshuazhuang2024@u.northwestern.edu",
  },
  {
    firstName: "Samantha",
    lastName: "Bittle",
    cellPhone: "(443)752-5263",
    emailAddress: "scbittle@gmail.com",
  },
  {
    firstName: "Rachel",
    lastName: "Frazier",
    cellPhone: "(630)862-9715",
    emailAddress: "racfrazier1@gmail.com",
  },
  {
    firstName: "Michelle",
    lastName: "Guzman",
    cellPhone: "(956)341-4216",
    emailAddress: "michelleguzman2024@u.northwestern.edu",
  },
  {
    firstName: "Sean",
    lastName: "Keenan",
    cellPhone: "(719)351-5839",
    emailAddress: "keenanrecording@gmail.com",
  },
  {
    firstName: "Nick",
    lastName: "Lin",
    cellPhone: "(847)347-9510",
    emailAddress: "nick@peckhammp.com",
  },
  {
    firstName: "Matt",
    lastName: "Peckham",
    cellPhone: "(218)269-0626",
    emailAddress: "matt@peckhammp.com",
  },
  {
    firstName: "Amanda",
    lastName: "Swanson",
    cellPhone: "(815)531-5267",
    emailAddress: "amandaswanson2020@u.northwestern.edu",
  },
  {
    firstName: "Michael",
    lastName: "Turner",
    cellPhone: "(312)459-8839",
    emailAddress: "michaelturner2023@u.northwestern.edu",
  },
  {
    firstName: "Austin",
    lastName: "Williams",
    cellPhone: "(651)472-4739",
    emailAddress: "austingwilliamsmusic@gmail.com",
  },
  {
    firstName: "Bill",
    lastName: "Milgram",
    cellPhone: "(847)641-0155",
    emailAddress: "w-milgram@northwestern.edu",
  },
  {
    firstName: "Henry",
    lastName: "Stewart",
    cellPhone: "(574)326-9842",
    emailAddress: "henry.stewart@northwestern.edu",
  },
];
